.TH MAGICOR 1 "January 17, 2007"
.SH NAME
Magicor \- Puzzle game in the spirit of solomon's key
.SH SYNOPSIS
.B magicor
[\fIOPTION\fR]
.SH DESCRIPTION
Magicor is a small puzzle game similar to the old NES classic
solomon's key. You control tux the penguin and create ice blocks
to extinguish all fires on each map.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
show this help message and exit
.TP
\fB\-c CONFIGPATH\fR, \fB\-\-config=CONFIGPATH\fR
use this default config, default /etc/magicor.conf
.TP
\fB\-j JOYSTICK\fR, \fB\-\-joystick=JOYSTICK\fR
enable/disable joystick
.TP
\fB\-m MUSIC\fR, \fB\-\-music=MUSIC\fR
enable/disable music
.TP
\fB\-s SOUND\fR, \fB\-\-sound=SOUND\fR
enable/disable sound
.TP
\fB\-f FULLSCREEN\fR, \fB\-\-fullscreen=FULLSCREEN\fR
enable/disable fullscreen
.SH "SEE ALSO"
.PP
http://magicor.sf.net/
.SH AUTHOR
Magicor was written by peter gebauer <petgeb@sf.net>.

.PP
This manual page was written by Xavier Oswald,
for the Debian project (but may be used by others).
